### ISSUE TITLE
arpa/nameser.h not available on Windows

### ISSUE THREAD

**Issue by pjknowles** [molpro/gci#14]
In GitLab by @ajmay81 on Aug 13, 2019, 10:37

Introduced in 8aba649 results in:

```
../dependencies/gci/lib/gciDavidson.cpp:4:10: fatal error: arpa/nameser.h: No such file or directory
 #include <arpa/nameser.h>
```

If I simply remove this include then it still compiles on Linux and allows compilation on Windows to proceed, so I wonder what is it's purpose and whether it can just be removed?
